(() => {
  "use strict";
  const $ = id => document.getElementById(id);
  const TAU = Math.PI * 2;
  const rand = (a=0,b=1) => a + Math.random()*(b-a);
  const clamp = (v,a,b) => Math.max(a,Math.min(b,v));
  const pick = a => a[Math.floor(Math.random()*a.length)];
  const canvas = $("game");
  if (!canvas) throw new Error("Missing #game canvas");
  const ctx = canvas.getContext("2d", {alpha:false});
  const screens = [...document.querySelectorAll(".screen")];
  const SAVE_KEY = "chimera-loop-save-v4";

  const ORIGINS = {
    razorborn:{icon:"🦷",name:"Razorborn",color:"#ff6f9f",desc:"Close-range predator. Dashing through prey primes critical volleys.",bonuses:["Fast movement","High critical chance","Bone volley"],hp:96,speed:245,damage:18,rate:.55,crit:.14},
    mycelial:{icon:"🍄",name:"Mycelial Host",color:"#9dff7c",desc:"Durable colony that spreads poison and recycles corpses.",bonuses:["High health","Poison attacks","Spore healing"],hp:132,speed:195,damage:15,rate:.68,crit:.05,poison:4},
    voltling:{icon:"⚡",name:"Voltling",color:"#66d9ff",desc:"Fragile storm organism that chains attacks across crowds.",bonuses:["Fast attacks","Chain lightning","Extra reroll"],hp:102,speed:220,damage:14,rate:.42,crit:.08,chain:1}
  };

  const MUTATIONS = {
    boneNeedles:{icon:"🗡",name:"Bone Needles",rarity:"common",tags:["bone","projectile"],max:5,desc:r=>`+1 projectile; volleys deal +${15+r*10}% damage.`},
    boneArms:{icon:"🦴",name:"Auxiliary Arms",rarity:"rare",tags:["bone","weapon"],max:4,desc:r=>`${1+r} autonomous bone arms fire at nearby prey.`},
    cathedral:{icon:"♜",name:"Bone Cathedral",rarity:"apex",tags:["bone","apex"],max:1,requires:["boneNeedles","boneArms"],desc:()=>"Every 20 kills grows another permanent weapon arm."},
    rapidSynapse:{icon:"⌁",name:"Rapid Synapse",rarity:"common",tags:["nerve","speed"],max:5,desc:r=>`Attack ${18+r*10}% faster.`},
    reflexLoop:{icon:"⟳",name:"Reflex Loop",rarity:"rare",tags:["nerve","dash"],max:3,desc:r=>`Dash slows enemies and primes ${1+r} guaranteed critical shots.`},
    hiveMind:{icon:"◉",name:"Hive Mind",rarity:"apex",tags:["nerve","apex"],max:1,requires:["rapidSynapse","droneNode"],desc:()=>"Replace the main volley with six independent neural drones."},
    venomSac:{icon:"☠",name:"Venom Sac",rarity:"uncommon",tags:["plague","dot"],max:5,desc:r=>`Hits inflict ${7+r*5} poison DPS.`},
    plagueBloom:{icon:"✿",name:"Plague Bloom",rarity:"rare",tags:["plague","area"],max:4,desc:r=>`Poisoned deaths burst for ${35+r*22} damage.`},
    carrionGarden:{icon:"♣",name:"Carrion Garden",rarity:"apex",tags:["plague","apex"],max:1,requires:["venomSac","plagueBloom"],desc:()=>"Corpses grow toxic flowers that attack for 12 seconds."},
    twinHeart:{icon:"♥",name:"Twin Heart",rarity:"common",tags:["blood","health"],max:5,desc:r=>`Gain ${26+r*14} maximum health and heal.`},
    novaHeart:{icon:"✹",name:"Nova Heart",rarity:"rare",tags:["blood","area"],max:4,desc:r=>`Each heartbeat erupts for ${42+r*25} damage; faster at low HP.`},
    bloodEngine:{icon:"♦",name:"Blood Engine",rarity:"apex",tags:["blood","apex"],max:1,requires:["twinHeart","novaHeart"],desc:()=>"Attack cooldowns spend health instead of time; kills restore health."},
    voltaicNode:{icon:"ϟ",name:"Voltaic Node",rarity:"uncommon",tags:["storm","chain"],max:5,desc:r=>`Chain to ${1+r} extra targets.`},
    stormHalo:{icon:"☼",name:"Storm Halo",rarity:"rare",tags:["storm","orbit"],max:4,desc:r=>`${2+r} lightning nodes orbit and zap nearby enemies.`},
    livingTempest:{icon:"☈",name:"Living Tempest",rarity:"apex",tags:["storm","apex"],max:1,requires:["voltaicNode","stormHalo"],desc:()=>"Continuous lightning lashes every enemy inside your storm field."},
    glassCore:{icon:"◇",name:"Glass Core",rarity:"rare",tags:["glass","critical"],max:4,desc:r=>`+${15+r*9}% crit, but take 8% more damage.`},
    prismSkin:{icon:"△",name:"Prism Skin",rarity:"uncommon",tags:["glass","reflect"],max:4,desc:r=>`${12+r*8}% chance to reflect contact damage as shards.`},
    singularityEye:{icon:"◉",name:"Singularity Eye",rarity:"rare",tags:["gravity","control"],max:4,desc:r=>`Periodic gravity pulse pulls enemies inward with ${20+r*15}% force.`},
    orbitingSpines:{icon:"✺",name:"Orbiting Spines",rarity:"rare",tags:["orbit","melee"],max:4,desc:r=>`${2+r} physical spines orbit your body.`},
    adrenalGland:{icon:"💨",name:"Adrenal Gland",rarity:"common",tags:["dash","speed"],max:5,desc:r=>`Move ${14+r*8}% faster; shorter dash cooldown.`},
    dashSpines:{icon:"➤",name:"Dash Spines",rarity:"uncommon",tags:["dash","impact"],max:4,desc:r=>`Dashing deals ${40+r*28} impact damage.`},
    predatoryMaw:{icon:"🦈",name:"Predatory Maw",rarity:"uncommon",tags:["devour","sustain"],max:4,desc:r=>`Every ${Math.max(2,6-r)} kills devours biomass and heals.`},
    devour:{icon:"◒",name:"Devour Organ",rarity:"rare",tags:["devour","loot"],max:3,desc:r=>`Elite kills can be digested into temporary organs (${20+r*10}% chance).`},
    droneNode:{icon:"⬡",name:"Drone Node",rarity:"uncommon",tags:["nerve","summon"],max:4,desc:r=>`${1+r} neural drone circles you and fires independently.`},
    hungryCortex:{icon:"◌",name:"Hungry Cortex",rarity:"common",tags:["growth","loot"],max:5,desc:r=>`+${18+r*10}% pickup radius and biomass gain.`},
    scavengerGut:{icon:"▣",name:"Scavenger Gut",rarity:"uncommon",tags:["loot","economy"],max:4,desc:r=>`Caches drop ${1+r} additional organ fragments.`},
    phaseMembrane:{icon:"◐",name:"Phase Membrane",rarity:"rare",tags:["defense","dash"],max:3,desc:r=>`After dashing, phase through enemies for ${.35+r*.15}s.`},
    compoundVision:{icon:"👁",name:"Compound Vision",rarity:"uncommon",tags:["vision","risk"],max:3,desc:r=>`See objectives farther away; enemies move ${5+r*4}% faster but drop more loot.`},
    chronoGland:{icon:"⌛",name:"Chrono Gland",rarity:"rare",tags:["time","control"],max:3,desc:r=>`Every ${10-r*2}s briefly slows all enemies.`},
    parasiteBrood:{icon:"⚉",name:"Parasite Brood",rarity:"rare",tags:["summon","plague"],max:3,desc:r=>`${2+r} larvae hatch from elite corpses and hunt nearby prey.`}
  };

  const META={carapace:{name:"Carapace",max:8,cost:8},tendons:{name:"Tendons",max:8,cost:8},cortex:{name:"Cortex",max:8,cost:10},instinct:{name:"Instinct",max:8,cost:11},adaptation:{name:"Adaptation",max:6,cost:14},recycling:{name:"Recycling",max:8,cost:12}};
  const defaultSave=()=>({genes:0,meta:Object.fromEntries(Object.keys(META).map(k=>[k,0])),bestTime:0,bestKills:0,bossKills:0,runs:0,muted:false});
  let save; try{save={...defaultSave(),...(JSON.parse(localStorage.getItem(SAVE_KEY)||"null")||{})};save.meta={...defaultSave().meta,...save.meta};}catch{save=defaultSave();}
  let game=null,lastOrigin="razorborn",last=performance.now(),W=innerWidth,H=innerHeight,dpr=1;
  const keys=new Set();
  const E={hud:$("hud"),time:$("hud-time"),level:$("hud-level"),kills:$("hud-kills"),hpFill:$("hp-fill"),hpLabel:$("hp-label"),xpFill:$("xp-fill"),xpLabel:$("xp-label"),build:$("build-strip"),gene:$("gene-count"),labGene:$("lab-gene-count"),bestTime:$("best-time"),bestKills:$("best-kills"),bossKills:$("boss-kills"),originGrid:$("origin-grid"),labGrid:$("lab-grid"),choiceGrid:$("choice-grid"),rerollCount:$("reroll-count"),reroll:$("reroll-button"),toast:$("toast-layer"),test:$("test-output"),resultTime:$("result-time"),resultKills:$("result-kills"),resultLevel:$("result-level"),resultGenes:$("result-genes"),resultBuild:$("result-build"),resultTitle:$("result-title"),resultEyebrow:$("result-eyebrow"),resultSubtitle:$("result-subtitle")};

  function persist(){localStorage.setItem(SAVE_KEY,JSON.stringify(save));refreshMenu();}
  function fmt(s){s=Math.floor(Math.max(0,s));return `${String(Math.floor(s/60)).padStart(2,"0")}:${String(s%60).padStart(2,"0")}`;}
  function show(id=null){screens.forEach(s=>s.classList.toggle("visible",s.id===id));}
  function toast(t){if(!E.toast)return;const n=document.createElement("div");n.className="toast";n.textContent=t;E.toast.appendChild(n);setTimeout(()=>n.remove(),1800);}
  function refreshMenu(){if(E.gene)E.gene.textContent=`${save.genes} genes`;if(E.labGene)E.labGene.textContent=save.genes;if(E.bestTime)E.bestTime.textContent=fmt(save.bestTime);if(E.bestKills)E.bestKills.textContent=save.bestKills;if(E.bossKills)E.bossKills.textContent=save.bossKills;}
  function renderOrigins(){E.originGrid.innerHTML=Object.entries(ORIGINS).map(([id,o])=>`<button class="origin-card" data-origin="${id}"><div class="origin-icon">${o.icon}</div><div class="eyebrow">STARTING BODY</div><h3>${o.name}</h3><p>${o.desc}</p><div class="origin-bonus">${o.bonuses.map(x=>`<span>${x}</span>`).join("")}</div></button>`).join("");E.originGrid.querySelectorAll("[data-origin]").forEach(b=>b.onclick=()=>startRun(b.dataset.origin));}
  function renderLab(){if(!E.labGrid)return;E.labGrid.innerHTML=Object.entries(META).map(([k,m])=>{const r=save.meta[k],c=Math.ceil(m.cost*(1+r*.65));return `<article class="lab-card"><h3>${m.name}</h3><p>Permanent rank ${r}/${m.max}</p><button data-meta="${k}" ${r>=m.max||save.genes<c?"disabled":""}>${r>=m.max?"MAX":`EVOLVE · ${c} GENES`}</button></article>`}).join("");E.labGrid.querySelectorAll("[data-meta]").forEach(b=>b.onclick=()=>{const k=b.dataset.meta,r=save.meta[k],c=Math.ceil(META[k].cost*(1+r*.65));if(save.genes>=c&&r<META[k].max){save.genes-=c;save.meta[k]++;persist();renderLab();}});}
  function rank(id){return game?.p.mutations[id]||0;}
  function has(id){return rank(id)>0;}
  function apexAvailable(m){return m.requires?.every(has);}
  function choices(){let pool=Object.entries(MUTATIONS).filter(([id,m])=>rank(id)<m.max&&(!m.requires||apexAvailable(m)));const out=[];while(pool.length&&out.length<3){const weighted=pool.flatMap(e=>Array(e[1].rarity==="common"?6:e[1].rarity==="uncommon"?3:e[1].rarity==="rare"?2:1).fill(e));const s=pick(weighted);out.push(s);pool=pool.filter(e=>e[0]!==s[0]);}game.choices=out;renderChoices();}
  function renderChoices(){E.rerollCount.textContent=`${game.rerolls} rerolls`;E.reroll.disabled=game.rerolls<=0;E.choiceGrid.innerHTML=game.choices.map(([id,m])=>`<button class="choice-card ${m.rarity==='apex'?'apex':''}" data-mutation="${id}"><div class="choice-icon">${m.icon}</div><div class="rarity">${m.rarity}</div><h3>${m.name}</h3><p>${m.desc(rank(id))}</p><div class="tag-list">${m.tags.map(t=>`<span class="tag">${t}</span>`).join("")}</div><div class="rank-line">RANK ${rank(id)} → ${rank(id)+1}</div></button>`).join("");E.choiceGrid.querySelectorAll("[data-mutation]").forEach(b=>b.onclick=()=>choose(b.dataset.mutation));}
  function choose(id){const old=rank(id);game.p.mutations[id]=old+1;if(id==="twinHeart"){const g=26+old*14;game.p.maxHp+=g;game.p.hp+=g;}game.mode="playing";show();toast(`${MUTATIONS[id].name} evolved`);updateHud(true);}

  function makePlayer(origin){const o=ORIGINS[origin],maxHp=o.hp+save.meta.carapace*8;return{x:0,y:0,r:18,hp:maxHp,maxHp,speed:o.speed*(1+save.meta.tendons*.03),damage:o.damage,rate:o.rate,fire:.2,crit:o.crit+save.meta.instinct*.015,poison:o.poison||0,chain:o.chain||0,xp:0,next:12,level:1,kills:0,mutations:{},dash:0,dashCd:0,inv:0,lastX:1,lastY:0,primed:0,nova:3,chrono:6,growthKills:0};}
  function startRun(origin=lastOrigin){lastOrigin=origin;game={mode:"playing",origin,p:makePlayer(origin),time:0,enemies:[],shots:[],pickups:[],particles:[],structures:[],companions:[],texts:[],spawn:.25,event:8,bossStage:0,rerolls:Math.floor((save.meta.adaptation+1)/2)+(origin==="voltling"?1:0),camera:{x:0,y:0},shake:0,choices:[],objective:null,biome:0,nextId:1};E.hud?.classList.remove("hidden");show();spawnStructure("cache",320,120);updateHud(true);toast(`${ORIGINS[origin].name} awakened`);}
  function spawnEnemy(type){const p=game.p,a=rand(0,TAU),d=rand(Math.max(W,H)*.55,Math.max(W,H)*.8),t=game.time;type=type||((t>120&&Math.random()<.18)?"brute":(t>45&&Math.random()<.25)?"dart":"crawler");let z=type==="brute"?{r:28,hp:85,speed:62,damage:18,color:"#ff8f70",xp:7}:type==="dart"?{r:13,hp:25,speed:165,damage:11,color:"#ffd76a",xp:3}:type==="elite"?{r:23,hp:260,speed:82,damage:20,color:"#ff6fb7",xp:18,elite:true}:{r:17,hp:38,speed:96,damage:12,color:"#bf72ff",xp:3};const scale=1+t/180;game.enemies.push({id:game.nextId++,type,x:p.x+Math.cos(a)*d,y:p.y+Math.sin(a)*d,maxHp:z.hp*scale,hp:z.hp*scale,...z,poison:0,dead:false,flash:0});}
  function spawnBoss(stage){const p=game.p;const mirror=stage===2;game.enemies.push({id:game.nextId++,type:mirror?"mirror":"collector",x:p.x+650,y:p.y,r:mirror?52:58,hp:mirror?3400:2200,maxHp:mirror?3400:2200,speed:mirror?68:52,damage:mirror?26:24,color:mirror?"#66d9ff":"#ff4b87",xp:100,boss:true,stage,dead:false,flash:0,ability:3});game.bossStage=stage;toast(mirror?"THE MIRROR HAS LEARNED YOUR BODY":"THE COLLECTOR HAS ENTERED");}
  function spawnStructure(type,x,y){game.structures.push({type,x:game.p.x+x,y:game.p.y+y,r:type==="shrine"?48:36,used:false,pulse:0});}
  function startEvent(){const type=pick(["hunt","cache","shrine","lab"]);if(type==="hunt"){game.objective={type,title:"PREDATOR TRIAL",remaining:35,target:22,progress:0};for(let i=0;i<4;i++)spawnEnemy("elite");toast("OBJECTIVE: KILL 22 BEFORE SIGNAL COLLAPSE");}else{const a=rand(0,TAU),d=rand(300,520);spawnStructure(type==="lab"?"lab":type,Math.cos(a)*d,Math.sin(a)*d);toast(type==="shrine"?"A BLOOD SHRINE IS CALLING":type==="lab"?"AN ABANDONED LAB HAS POWER":"AN ORGAN CACHE HAS FALLEN");}}
  function interactStructure(s){if(s.used)return;s.used=true;if(s.type==="cache"){for(let i=0;i<4+rank("scavengerGut");i++)game.pickups.push({x:s.x+rand(-25,25),y:s.y+rand(-25,25),kind:i===0?"organ":"xp",value:i===0?1:8,r:7,life:18});toast("CACHE OPENED");}else if(s.type==="shrine"){game.p.hp=Math.max(1,game.p.hp-game.p.maxHp*.22);game.p.damage*=1.32;for(let i=0;i<5;i++)spawnEnemy("elite");toast("THE SHRINE ACCEPTS BLOOD: +32% DAMAGE");}else if(s.type==="lab"){game.objective={type:"survive",title:"LAB ALARM",remaining:30,target:30,progress:0,structure:s};toast("LAB ALARM: SURVIVE 30 SECONDS");}}
  function nearest(x,y,range=9999,exclude=new Set()){let best=null,bd=range*range;for(const e of game.enemies){if(e.dead||exclude.has(e.id))continue;const d=(e.x-x)**2+(e.y-y)**2;if(d<bd){bd=d;best=e;}}return best;}
  function fire(x,y,target,damage,source="main"){const a=Math.atan2(target.y-y,target.x-x);game.shots.push({x,y,vx:Math.cos(a)*650,vy:Math.sin(a)*650,r:source==="drone"?3:4,damage,life:1.3,hit:new Set(),source});}
  function fireVolley(){const p=game.p,target=nearest(p.x,p.y,560);if(!target)return;if(has("hiveMind"))return;const count=1+rank("boneNeedles"),base=Math.atan2(target.y-p.y,target.x-p.x);for(let i=0;i<count;i++){const a=base+(i-(count-1)/2)*.12;game.shots.push({x:p.x,y:p.y,vx:Math.cos(a)*650,vy:Math.sin(a)*650,r:4,damage:p.damage*(1+rank("boneNeedles")*.15),life:1.3,hit:new Set(),source:"main"});}}
  function damageEnemy(e,dmg,crit=false){if(e.dead)return;e.hp-=dmg;e.flash=.08;game.texts.push({x:e.x,y:e.y-e.r,text:`${crit?'✦ ':''}${Math.round(dmg)}`,life:.55,color:crit?"#ffd76a":"#fff"});if(has("venomSac")||game.p.poison)e.poison=Math.max(e.poison,game.p.poison+rank("venomSac")*5+2);if(e.hp<=0)killEnemy(e);}
  function killEnemy(e){if(e.dead)return;e.dead=true;const p=game.p;p.kills++;p.growthKills++;if(game.objective?.type==="hunt")game.objective.progress++;const n=e.boss?14:e.elite?5:e.type==="brute"?3:1;for(let i=0;i<n;i++)game.pickups.push({x:e.x+rand(-18,18),y:e.y+rand(-18,18),kind:e.elite&&i===0?"organ":"xp",value:e.xp/n,r:6,life:20});if(has("plagueBloom")&&e.poison>0){for(const x of game.enemies)if(!x.dead&&(x.x-e.x)**2+(x.y-e.y)**2<150**2)damageEnemy(x,35+rank("plagueBloom")*22);}
    if(has("carrionGarden"))game.companions.push({type:"flower",x:e.x,y:e.y,life:12,fire:.2});if(has("parasiteBrood")&&(e.elite||Math.random()<.08))for(let i=0;i<1+rank("parasiteBrood");i++)game.companions.push({type:"larva",x:e.x,y:e.y,life:15,fire:.1});if(has("predatoryMaw")&&p.kills%Math.max(2,6-rank("predatoryMaw"))===0)p.hp=Math.min(p.maxHp,p.hp+5+rank("predatoryMaw")*2);if(has("cathedral")&&p.growthKills>=20){p.growthKills=0;p.mutations.boneArms=(p.mutations.boneArms||0)+1;toast("BONE CATHEDRAL GROWS ANOTHER ARM");}
    if(e.boss){save.bossKills++;game.biome=Math.min(2,game.biome+1);if(e.stage===2)setTimeout(()=>endRun(true),500);else toast("WARDEN BROKEN — THE BIOME OPENS");}}
  function damagePlayer(d){const p=game.p;if(p.inv>0||game.mode!=="playing")return;d*=has("glassCore")?1.08:1;p.hp-=d;p.inv=.5;game.shake=10;if(p.hp<=0)endRun(false);}
  function dash(){if(!game||game.mode!=="playing"||game.p.dashCd>0)return;const p=game.p;let x=(keys.has("KeyD")||keys.has("ArrowRight")?1:0)-(keys.has("KeyA")||keys.has("ArrowLeft")?1:0),y=(keys.has("KeyS")||keys.has("ArrowDown")?1:0)-(keys.has("KeyW")||keys.has("ArrowUp")?1:0),l=Math.hypot(x,y);if(l<.1){x=p.lastX;y=p.lastY}else{x/=l;y/=l}p.dx=x;p.dy=y;p.dash=.18;p.inv=.28+(has("phaseMembrane")?.2:0);p.dashCd=Math.max(.5,1.65-rank("adrenalGland")*.16);if(has("reflexLoop"))p.primed=1+rank("reflexLoop");game.shake=7;}
  function updatePlayer(dt){const p=game.p;p.inv=Math.max(0,p.inv-dt);p.dashCd=Math.max(0,p.dashCd-dt);let x=(keys.has("KeyD")||keys.has("ArrowRight")?1:0)-(keys.has("KeyA")||keys.has("ArrowLeft")?1:0),y=(keys.has("KeyS")||keys.has("ArrowDown")?1:0)-(keys.has("KeyW")||keys.has("ArrowUp")?1:0),l=Math.hypot(x,y);if(l>.05){x/=l;y/=l;p.lastX=x;p.lastY=y}if(p.dash>0){p.dash-=dt;p.x+=p.dx*780*dt;p.y+=p.dy*780*dt;if(has("dashSpines"))for(const e of game.enemies)if(!e.dead&&(e.x-p.x)**2+(e.y-p.y)**2<(e.r+35)**2)damageEnemy(e,40+rank("dashSpines")*28);}else{const sp=p.speed*(1+rank("adrenalGland")*.08);p.x+=x*sp*dt;p.y+=y*sp*dt;}
    p.fire-=dt;const attackRate=p.rate/(1+rank("rapidSynapse")*.1);if(p.fire<=0){fireVolley();p.fire=has("bloodEngine")?.08:attackRate;if(has("bloodEngine"))p.hp=Math.max(1,p.hp-.6);}
    p.nova-=dt;if(has("novaHeart")&&p.nova<=0){const hpFactor=clamp(p.hp/p.maxHp,.2,1);p.nova=2.8*hpFactor;for(const e of game.enemies)if(!e.dead&&(e.x-p.x)**2+(e.y-p.y)**2<210**2)damageEnemy(e,42+rank("novaHeart")*25);game.particles.push({x:p.x,y:p.y,r:90,life:.5,color:"#ff6f9f",ring:true});}
    p.chrono-=dt;if(has("chronoGland")&&p.chrono<=0){p.chrono=Math.max(4,10-rank("chronoGland")*2);game.slow=.7;toast("CHRONO GLAND DISCHARGE");}
    for(const s of game.structures)if(!s.used&&(s.x-p.x)**2+(s.y-p.y)**2<(s.r+p.r+8)**2)interactStructure(s);
  }
  function updateCompanions(dt){const p=game.p;const droneCount=rank("droneNode")+(has("hiveMind")?6:0)+rank("boneArms");for(let i=0;i<droneCount;i++){const a=game.time*(1.4+i*.03)+i/droneCount*TAU,x=p.x+Math.cos(a)*(65+(i%2)*18),y=p.y+Math.sin(a)*(65+(i%2)*18),t=nearest(x,y,450);if(t&&Math.floor((game.time+i*.13)*4)!==Math.floor((game.time-dt+i*.13)*4))fire(x,y,t,p.damage*(has("hiveMind")?.48:.35),"drone");}
    for(const c of game.companions){c.life-=dt;c.fire-=dt;const t=nearest(c.x,c.y,350);if(t&&c.fire<=0){fire(c.x,c.y,t,c.type==="flower"?12:8,"drone");c.fire=c.type==="flower"?.55:.75;}if(c.type==="larva"&&t){const a=Math.atan2(t.y-c.y,t.x-c.x);c.x+=Math.cos(a)*110*dt;c.y+=Math.sin(a)*110*dt;}}game.companions=game.companions.filter(c=>c.life>0);
  }
  function updateEnemies(dt){const p=game.p,slow=game.slow>0?.35:1;if(game.slow>0)game.slow-=dt;for(const e of game.enemies){if(e.dead)continue;e.flash=Math.max(0,e.flash-dt);if(e.poison>0){e.hp-=e.poison*dt;if(e.hp<=0){killEnemy(e);continue;}}let dx=p.x-e.x,dy=p.y-e.y,l=Math.hypot(dx,dy)||1;e.x+=dx/l*e.speed*slow*(1+rank("compoundVision")*.04)*dt;e.y+=dy/l*e.speed*slow*(1+rank("compoundVision")*.04)*dt;if(e.boss){e.ability-=dt;if(e.ability<=0){e.ability=e.stage===2?2.4:3.2;if(e.stage===1&&Object.keys(p.mutations).length){const id=pick(Object.keys(p.mutations));p.mutations[id]=Math.max(0,p.mutations[id]-1);toast(`THE COLLECTOR STOLE ${MUTATIONS[id].name}`);updateHud(true);}else{for(let i=0;i<8;i++){const a=i/8*TAU;game.shots.push({x:e.x,y:e.y,vx:Math.cos(a)*260,vy:Math.sin(a)*260,r:7,damage:11,life:2,enemy:true,hit:new Set()});}}}}if(l<p.r+e.r)damagePlayer(e.damage);}game.enemies=game.enemies.filter(e=>!e.dead);}
  function updateShots(dt){const p=game.p;for(const s of game.shots){s.x+=s.vx*dt;s.y+=s.vy*dt;s.life-=dt;if(s.enemy){if((s.x-p.x)**2+(s.y-p.y)**2<(s.r+p.r)**2){damagePlayer(s.damage);s.life=-1;}continue;}for(const e of game.enemies){if(e.dead||s.hit.has(e.id))continue;if((s.x-e.x)**2+(s.y-e.y)**2<(s.r+e.r)**2){s.hit.add(e.id);const crit=p.primed>0||Math.random()<p.crit+rank("glassCore")*.09;if(p.primed>0)p.primed--;const amount=s.damage*(crit?2.1:1);damageEnemy(e,amount,crit);let src=e,seen=new Set([e.id]);for(let i=0;i<p.chain+rank("voltaicNode");i++){const n=nearest(src.x,src.y,190,seen);if(!n)break;seen.add(n.id);damageEnemy(n,amount*.55);src=n;}s.life=-1;break;}}}game.shots=game.shots.filter(s=>s.life>0);}
  function updatePickups(dt){const p=game.p,mag=125+rank("hungryCortex")*45;for(const q of game.pickups){q.life-=dt;const dx=p.x-q.x,dy=p.y-q.y,l=Math.hypot(dx,dy)||1;if(l<mag){q.x+=dx/l*380*dt;q.y+=dy/l*380*dt;}if(l<p.r+q.r+6){q.life=-1;if(q.kind==="xp")p.xp+=q.value*(1+save.meta.cortex*.04+rank("hungryCortex")*.1);else{p.xp+=12;toast("TEMPORARY ORGAN ABSORBED");}}}game.pickups=game.pickups.filter(q=>q.life>0);if(p.xp>=p.next&&game.mode==="playing"){p.xp-=p.next;p.level++;p.next=Math.floor(12*Math.pow(1.27,p.level-1));game.mode="levelup";choices();show("level-screen");updateHud(true);}}
  function updateObjective(dt){const o=game.objective;if(!o)return;o.remaining-=dt;if(o.type==="survive")o.progress=o.target-o.remaining;if((o.type==="hunt"&&o.progress>=o.target)||(o.type==="survive"&&o.remaining<=0)){toast(`${o.title} COMPLETE — APEX ORGAN REWARD`);game.p.xp+=game.p.next*.8;game.pickups.push({x:game.p.x,y:game.p.y,kind:"organ",value:1,r:9,life:20});game.objective=null;}else if(o.remaining<=0){toast(`${o.title} FAILED`);game.objective=null;}}
  function update(dt){if(!game||game.mode!=="playing")return;game.time+=dt;if(game.time>90&&game.bossStage===0)spawnBoss(1);if(game.time>210&&game.bossStage===1&&!game.enemies.some(e=>e.boss))spawnBoss(2);game.spawn-=dt;if(game.spawn<=0){for(let i=0;i<1+Math.floor(game.time/90);i++)spawnEnemy();game.spawn=Math.max(.2,.78-game.time/600)*rand(.8,1.2);}game.event-=dt;if(game.event<=0){startEvent();game.event=rand(24,38);}updatePlayer(dt);updateCompanions(dt);updateEnemies(dt);updateShots(dt);updatePickups(dt);updateObjective(dt);game.camera.x+=(game.p.x-game.camera.x)*Math.min(1,dt*8);game.camera.y+=(game.p.y-game.camera.y)*Math.min(1,dt*8);game.shake=Math.max(0,game.shake-dt*25);updateHud();}
  function w2s(x,y,sx=0,sy=0){return{x:x-game.camera.x+W/2+sx,y:y-game.camera.y+H/2+sy};}
  const BIOMES=[{bg:"#071522",grid:"#66d9ff",accent:"#77ffbd",name:"SUNKEN NURSERY"},{bg:"#210b1b",grid:"#ff6fb7",accent:"#bf72ff",name:"VISCERAL FOUNDRY"},{bg:"#181203",grid:"#ffd76a",accent:"#ff667a",name:"WARDEN'S NULL"}];
  function drawBackground(sx,sy){const b=BIOMES[game.biome];ctx.fillStyle=b.bg;ctx.fillRect(0,0,W,H);const g=ctx.createRadialGradient(W*.5,H*.45,40,W*.5,H*.45,Math.max(W,H)*.8);g.addColorStop(0,b.accent+"22");g.addColorStop(1,"#00000000");ctx.fillStyle=g;ctx.fillRect(0,0,W,H);for(let layer=0;layer<3;layer++){const sp=95+layer*80,ox=(((-game.camera.x*(.08+layer*.05))%sp)+sp)%sp,oy=(((-game.camera.y*(.08+layer*.05))%sp)+sp)%sp;ctx.strokeStyle=b.grid+(layer===0?"22":"10");ctx.lineWidth=1+layer*.4;ctx.beginPath();for(let x=ox;x<W;x+=sp){ctx.moveTo(x,0);for(let y=0;y<H;y+=35)ctx.lineTo(x+Math.sin(y*.018+game.time*.5+layer)*12,y);}for(let y=oy;y<H;y+=sp){ctx.moveTo(0,y);ctx.lineTo(W,y);}ctx.stroke();}for(let i=0;i<45;i++){const x=(i*137+game.time*(8+i%3)*.6)%W,y=(i*83+Math.sin(game.time+i)*30+H)%H;ctx.fillStyle=i%2?b.accent+"44":b.grid+"44";ctx.fillRect(x,y,1+i%3,1+i%3);}}
  function drawPlayer(sx,sy){const p=game.p,b=BIOMES[game.biome],s=w2s(p.x,p.y,sx,sy);ctx.save();ctx.translate(s.x,s.y);ctx.rotate(Math.atan2(p.lastY,p.lastX));ctx.globalAlpha=p.inv>0&&Math.floor(game.time*18)%2?.35:1;ctx.fillStyle=ORIGINS[game.origin].color;ctx.shadowBlur=24;ctx.shadowColor=ORIGINS[game.origin].color;ctx.beginPath();ctx.ellipse(0,0,p.r*1.25,p.r*.9,0,0,TAU);ctx.fill();ctx.shadowBlur=0;if(has("twinHeart")||has("novaHeart")){ctx.strokeStyle="#ff6fb7";ctx.lineWidth=2+rank("novaHeart");ctx.beginPath();ctx.arc(0,0,27+Math.sin(game.time*7)*3,0,TAU);ctx.stroke();}if(has("glassCore")){ctx.strokeStyle="#ffd76a";ctx.rotate(game.time*.7);ctx.beginPath();for(let i=0;i<6;i++){const a=i/6*TAU;i?ctx.lineTo(Math.cos(a)*30,Math.sin(a)*25):ctx.moveTo(Math.cos(a)*30,Math.sin(a)*25);}ctx.closePath();ctx.stroke();}if(has("venomSac"))for(let i=0;i<Math.min(5,rank("venomSac")+1);i++){ctx.fillStyle="#9dff7c88";ctx.beginPath();ctx.arc(-8+i*5,12+Math.sin(game.time*3+i)*3,4+i%2,0,TAU);ctx.fill();}if(has("boneNeedles")||has("dashSpines")){ctx.strokeStyle="#eefdf8";ctx.lineWidth=2;const n=5+rank("boneNeedles");for(let i=0;i<n;i++){const a=i/n*TAU;ctx.beginPath();ctx.moveTo(Math.cos(a)*18,Math.sin(a)*14);ctx.lineTo(Math.cos(a)*(30+rank("boneNeedles")*2),Math.sin(a)*(25+rank("boneNeedles")*2));ctx.stroke();}}if(has("voltaicNode")){ctx.strokeStyle="#66d9ff";for(let i=0;i<6;i++){const a=i/6*TAU+game.time;ctx.beginPath();ctx.moveTo(Math.cos(a)*20,Math.sin(a)*15);ctx.lineTo(Math.cos(a+.2)*35,Math.sin(a+.2)*28);ctx.stroke();}}if(has("predatoryMaw")){ctx.strokeStyle=b.accent;ctx.lineWidth=3;ctx.beginPath();ctx.arc(12,0,12,-.8,.8);ctx.stroke();}ctx.fillStyle="#06100d";ctx.beginPath();ctx.arc(8,-5,3,0,TAU);ctx.arc(8,5,3,0,TAU);ctx.fill();ctx.restore();}
  function draw(){if(!game){ctx.fillStyle="#070a14";ctx.fillRect(0,0,W,H);return;}const sx=game.shake?rand(-game.shake,game.shake):0,sy=game.shake?rand(-game.shake,game.shake):0;drawBackground(sx,sy);for(const s of game.structures){const q=w2s(s.x,s.y,sx,sy);ctx.strokeStyle=s.used?"#555":s.type==="shrine"?"#ff667a":s.type==="lab"?"#66d9ff":"#ffd76a";ctx.lineWidth=3;ctx.beginPath();ctx.arc(q.x,q.y,s.r+Math.sin(game.time*3)*4,0,TAU);ctx.stroke();ctx.fillStyle=ctx.strokeStyle+"33";ctx.fill();ctx.fillStyle="#fff";ctx.font="22px system-ui";ctx.textAlign="center";ctx.fillText(s.type==="shrine"?"♥":s.type==="lab"?"⌬":"▣",q.x,q.y+7);}for(const q of game.pickups){const s=w2s(q.x,q.y,sx,sy);ctx.fillStyle=q.kind==="organ"?"#ffd76a":"#77ffbd";ctx.shadowBlur=10;ctx.shadowColor=ctx.fillStyle;ctx.beginPath();ctx.arc(s.x,s.y,q.r,0,TAU);ctx.fill();ctx.shadowBlur=0;}for(const sh of game.shots){const s=w2s(sh.x,sh.y,sx,sy);ctx.fillStyle=sh.enemy?"#ff667a":sh.source==="drone"?"#66d9ff":"#effff8";ctx.beginPath();ctx.arc(s.x,s.y,sh.r,0,TAU);ctx.fill();}for(const c of game.companions){const s=w2s(c.x,c.y,sx,sy);ctx.fillStyle=c.type==="flower"?"#9dff7c":"#ff6fb7";ctx.beginPath();ctx.arc(s.x,s.y,c.type==="flower"?9:6,0,TAU);ctx.fill();}for(const e of game.enemies){const s=w2s(e.x,e.y,sx,sy);ctx.save();ctx.translate(s.x,s.y);ctx.fillStyle=e.flash>0?"#fff":e.color;ctx.shadowBlur=e.boss?30:10;ctx.shadowColor=e.color;ctx.beginPath();const n=e.boss?12:e.type==="brute"?8:6;for(let i=0;i<n;i++){const a=i/n*TAU,r=e.r*(i%2?.75:1);i?ctx.lineTo(Math.cos(a)*r,Math.sin(a)*r):ctx.moveTo(Math.cos(a)*r,Math.sin(a)*r);}ctx.closePath();ctx.fill();ctx.restore();if(e.boss){ctx.fillStyle="#000a";ctx.fillRect(s.x-85,s.y-e.r-16,170,7);ctx.fillStyle=e.color;ctx.fillRect(s.x-85,s.y-e.r-16,170*clamp(e.hp/e.maxHp,0,1),7);}}drawPlayer(sx,sy);for(const t of game.texts){const s=w2s(t.x,t.y,sx,sy);ctx.globalAlpha=clamp(t.life*2,0,1);ctx.fillStyle=t.color;ctx.font="800 13px system-ui";ctx.textAlign="center";ctx.fillText(t.text,s.x,s.y);t.life-=.016;t.y-=.5;}ctx.globalAlpha=1;game.texts=game.texts.filter(t=>t.life>0);if(game.objective){ctx.fillStyle="#07111ddd";ctx.fillRect(W/2-190,18,380,58);ctx.fillStyle="#fff";ctx.font="900 14px system-ui";ctx.textAlign="center";ctx.fillText(game.objective.title,W/2,42);ctx.fillStyle="#ffd76a";ctx.fillText(`${game.objective.type==='hunt'?`${game.objective.progress}/${game.objective.target}`:`${Math.ceil(game.objective.remaining)}s`} · ${Math.ceil(game.objective.remaining)}s`,W/2,63);}}
  function updateHud(force=false){if(!game)return;const p=game.p;E.time.textContent=fmt(game.time);E.level.textContent=p.level;E.kills.textContent=p.kills;E.hpFill.style.width=`${clamp(p.hp/p.maxHp*100,0,100)}%`;E.hpLabel.textContent=`${Math.ceil(Math.max(0,p.hp))} / ${Math.ceil(p.maxHp)}`;E.xpFill.style.width=`${clamp(p.xp/p.next*100,0,100)}%`;E.xpLabel.textContent=`${Math.floor(p.xp)} / ${p.next}`;if(force)E.build.innerHTML=Object.entries(p.mutations).filter(([,r])=>r>0).map(([id,r])=>`<span class="build-chip">${MUTATIONS[id].icon} ${MUTATIONS[id].name} ${r}</span>`).join("");if(E.test)E.test.textContent=JSON.stringify({boot:true,mode:game.mode,time:game.time,level:p.level,enemies:game.enemies.length,structures:game.structures.length,objective:game.objective?.type||null});}
  function endRun(victory){if(!game||game.mode==="gameover")return;game.mode="gameover";const p=game.p,genes=Math.floor((Math.max(1,Math.floor(p.kills/9)+Math.floor(game.time/20)+(victory?40:0)))*(1+save.meta.recycling*.06));save.genes+=genes;save.runs++;save.bestTime=Math.max(save.bestTime,game.time);save.bestKills=Math.max(save.bestKills,p.kills);persist();E.resultTime.textContent=fmt(game.time);E.resultKills.textContent=p.kills;E.resultLevel.textContent=p.level;E.resultGenes.textContent=`+${genes}`;E.resultEyebrow.textContent=victory?"MIRROR DISASSEMBLED":"BODY TERMINATED";E.resultTitle.textContent=victory?"The abyss copied you and failed.":"The loop remembers.";E.resultSubtitle.textContent=victory?"Your impossible anatomy has been archived.":"Useful organs were recovered for the next body.";E.resultBuild.innerHTML=E.build.innerHTML;E.hud.classList.add("hidden");show("gameover-screen");}
  function pause(){if(!game)return;if(game.mode==="playing"){game.mode="paused";show("pause-screen");}else if(game.mode==="paused"){game.mode="playing";show();}}
  function resize(){dpr=Math.min(2,devicePixelRatio||1);W=innerWidth;H=innerHeight;canvas.width=Math.round(W*dpr);canvas.height=Math.round(H*dpr);ctx.setTransform(dpr,0,0,dpr,0,0);}
  function loop(now){const dt=Math.min(.035,(now-last)/1000);last=now;update(dt);draw();requestAnimationFrame(loop);}

  $("play-button")?.addEventListener("click",()=>show("origin-screen"));
  $("lab-button")?.addEventListener("click",()=>{renderLab();show("lab-screen")});
  $("help-button")?.addEventListener("click",()=>show("help-screen"));
  $("close-help-button")?.addEventListener("click",()=>show("menu-screen"));
  document.querySelectorAll('[data-back="menu"]').forEach(b=>b.addEventListener("click",()=>show("menu-screen")));
  $("pause-button")?.addEventListener("click",pause);$("resume-button")?.addEventListener("click",pause);$("touch-dash")?.addEventListener("click",dash);
  $("restart-button")?.addEventListener("click",()=>startRun(lastOrigin));$("quit-button")?.addEventListener("click",()=>{E.hud.classList.add("hidden");game=null;show("menu-screen")});
  $("again-button")?.addEventListener("click",()=>startRun(lastOrigin));$("result-menu-button")?.addEventListener("click",()=>{game=null;show("menu-screen")});$("result-lab-button")?.addEventListener("click",()=>{renderLab();show("lab-screen")});
  E.reroll?.addEventListener("click",()=>{if(game?.rerolls>0){game.rerolls--;choices();}});
  $("reset-save-button")?.addEventListener("click",()=>{if(confirm("Reset all progression?")){save=defaultSave();persist();renderLab();}});
  addEventListener("keydown",e=>{keys.add(e.code);if(e.code==="Space"){e.preventDefault();dash()}if(e.code==="Escape")pause();});addEventListener("keyup",e=>keys.delete(e.code));addEventListener("resize",resize);
  resize();refreshMenu();renderOrigins();requestAnimationFrame(loop);
  window.__CHIMERA_READY__=true;
})();